# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.1.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}{{ checksum "browser-tests/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: npm install
      - run: cd browser-tests && npm install

      - save_cache:
          paths:
            - node_modules
            - browser-tests/node_modules
          key: v2-dependencies-{{ checksum "package.json" }}{{ checksum "browser-tests/package.json" }}

      # run tests!
      - run: npm -s run ci
      - run: cd browser-tests && npm -s run test
